server:
  port: 8082

spring:
  kafka:
    consumer:
      consumer-milktea:
        group-id: "milktea_id"
        topic: "milktea"
      consumer-greentea:
        group-id: "greentea_id"
        topic: "greentea"
      bootstrap-servers: "127.0.0.1:9092"
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
